src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`orders`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $door_width;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $door_height;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $handle_side;

    /**
     * @ORM\OneToMany(targetEntity=Window::class, mappedBy="booking")
     */
    private $windows;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     */
    private $user_order;

    public function __construct()
    {
        $this->windows = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDoorWidth(): ?string
    {
        return $this->door_width;
    }

    public function setDoorWidth(string $door_width): self
    {
        $this->door_width = $door_width;

        return $this;
    }

    public function getDoorHeight(): ?string
    {
        return $this->door_height;
    }

    public function setDoorHeight(string $door_height): self
    {
        $this->door_height = $door_height;

        return $this;
    }

    public function getHandleSide(): ?string
    {
        return $this->handle_side;
    }

    public function setHandleSide(string $handle_side): self
    {
        $this->handle_side = $handle_side;

        return $this;
    }

    /**
     * @return Collection|Window[]
     */
    public function getWindows(): Collection
    {
        return $this->windows;
    }

    public function addWindow(Window $window): self
    {
        if (!$this->windows->contains($window)) {
            $this->windows[] = $window;
            $window->setBooking($this);
        }

        return $this;
    }

    public function removeWindow(Window $window): self
    {
        if ($this->windows->removeElement($window)) {
            // set the owning side to null (unless already changed)
            if ($window->getBooking() === $this) {
                $window->setBooking(null);
            }
        }

        return $this;
    }

    public function getUserOrder(): ?User
    {
        return $this->user_order;
    }

    public function setUserOrder(?User $user_order): self
    {
        $this->user_order = $user_order;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('door_width')
            ->add('door_height')
            ->add('handle_side')
            // ->add('created_at')
            // ->add('updated_at')
            // ->add('user_order')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\OrderType;
use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/order")
 */
class OrderController extends AbstractController
{
    /**
     * @Route("/", name="order_index", methods={"GET"})
     */
    public function index(OrderRepository $orderRepository): Response
    {
        return $this->render('order/index.html.twig', [
            'orders' => $orderRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="order_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $order = new Order();
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('order/new.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="order_show", methods={"GET"})
     */
    public function show(Order $order): Response
    {
        return $this->render('order/show.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="order_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Order $order): Response
    {
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('order/edit.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="order_delete", methods={"POST"})
     */
    public function delete(Request $request, Order $order): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('order_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/order/_delete_form.html.twig
<form method="post" action="{{ path('order_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/order/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <h1>Edit Order</h1>

    {{ include('order/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('order_index') }}">back to list</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order index{% endblock %}

{% block body %}
    <h1>Order index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Door_width</th>
                <th>Door_height</th>
                <th>Handle_side</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.name }}</td>
                <td>{{ order.doorWidth }}</td>
                <td>{{ order.doorHeight }}</td>
                <td>{{ order.handleSide }}</td>
                <td>{{ order.createdAt ? order.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ order.updatedAt ? order.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('order_show', {'id': order.id}) }}">show</a>
                    <a href="{{ path('order_edit', {'id': order.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('order_new') }}">Create new</a>
{% endblock %}

templates/order/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Order{% endblock %}

{% block body %}
    <h1>Create new Order</h1>

    {{ include('order/_form.html.twig') }}

    <a href="{{ path('order_index') }}">back to list</a>
{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    <h1>Order</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ order.name }}</td>
            </tr>
            <tr>
                <th>Door_width</th>
                <td>{{ order.doorWidth }}</td>
            </tr>
            <tr>
                <th>Door_height</th>
                <td>{{ order.doorHeight }}</td>
            </tr>
            <tr>
                <th>Handle_side</th>
                <td>{{ order.handleSide }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ order.createdAt ? order.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ order.updatedAt ? order.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('order_index') }}">back to list</a>

    <a href="{{ path('order_edit', {'id': order.id}) }}">edit</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}